### ISSUE TITLE
can't find library "libtensorflowlite_c.so"

### ISSUE THREAD

**Issue by lirazhad** [Rajatkalsotra/Face-Recognition-Flutter#8]
i get this exception Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libtensorflowlite_c.so" not found), and i don't know how to install this library.

**Comment by Rajatkalsotra** [comment]
Please go through the following link:

https://github.com/Rajatkalsotra/Face-Recognition-Flutter/issues/6#issuecomment-716310245

**Comment by lirazhad** [comment]
thanks @Rajatkalsotra , is this project should also work in iOS?

**Comment by khalidlionel** [comment]
I got this error 
 [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (undefined symbol: TfLiteGpuDelegateV2Create).
by the way i downloaded the the install.bat file and executed the install.bat command

**Comment by fuadarradhi** [comment]
@khalidlionel install with `-d` option,
https://pub.dev/packages/tflite_flutter

**Comment by rmunia** [comment]
> 

@khalid-alsaleh-dev Could you kindly tell me how did you place the install.bat file and execute the command? I am confused where to place this place and where to execute the command.

**Comment by tayabdev** [comment]
It is because this URL is not accessible to the desired file
set URL=https://github.com/am15h/tflite_flutter_plugin/releases/download/
![notFoudIssue](https://user-images.githubusercontent.com/92080343/233682210-6140ba54-c3c1-4059-85da-2c86c04c6546.png)
![pubDevIssue2](https://user-images.githubusercontent.com/92080343/233682222-83ba2eb7-37c7-4b7f-a8a2-2af83de2cf8c.png)

**Comment by tayabdev** [comment]
> install

Place your file inside lib and inside lib run .\install.bat from your terminal
